"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xta&gj(e&c#jn74+m0p4f*3-r0#%@11f+0l@ua#m^c(mac#vnb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Saller',
    'djcelery',
]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Qshop.middlewaretest.MiddleWareTest',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    # 'slave': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db2.sqlite3'),
    # },
    # 'slave2': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db3.sqlite3'),
    # }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)
# 这条配置跟STATICFILES_DIRS、MEDIA_URL、MEDIA_ROOT这三个冲突
# 在做静态文件收集的时候需要，如果收集完成之后，将下面这条注释掉
# STATIC_ROOT = os.path.join(BASE_DIR,'static')


#媒体文件
MEDIA_URL = '/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'static')


# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION':[
#             '127.0.0.1:11211'  # 本地memcache的地址  端口
#         ]
#     }
# }
# CACHE_MIDDLEWARE_KEY_PREFIX = ''
# CACHE_MIDDLEWARE_SECONDS = 600
# CACHE_MIDDLEWARE_ALIAS = 'default'


# DATABASE_ROUTERS = ['mydbrouter.Router',]

# logging日志的配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # 是否禁用之前的日志
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR,'debug.log')
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}





# 公钥
alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA64MmgYBsiDjFVUFPi+ZMkAx0SyeVe43pjhY7CJ28Tuhf7pjXJC9uKuecoqg7GbpSDJSufm+nAkpD1MYqTQFCqRps/e6+MYvIXysHq+hpPLrBnU8VydFmE5t0geCb3tysQbb+qLN8eh9YsJPOjHfG7Fyxp45vmEmyeHvWCLYXs4cjDauqfIrHMJ/KnCDS/bVVyxv6X4Cs0pAsASu1UXL+c9tXNSuFLRh8lNh4LkTTpVmzf4oE5rFoPaYJm8VXRbCqvgh37w5avjCx1hhbUdT8wAKEkPXpjNEsog0uyw8IomBRICnYvaSkcgx1EeCzW8kLW1xvzPsiYRGlJtaRxw0FiwIDAQAB
    -----END PUBLIC KEY-----"""

    # 私钥
alipay_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
    MIIEpgIBAAKCAQEA64MmgYBsiDjFVUFPi+ZMkAx0SyeVe43pjhY7CJ28Tuhf7pjXJC9uKuecoqg7GbpSDJSufm+nAkpD1MYqTQFCqRps/e6+MYvIXysHq+hpPLrBnU8VydFmE5t0geCb3tysQbb+qLN8eh9YsJPOjHfG7Fyxp45vmEmyeHvWCLYXs4cjDauqfIrHMJ/KnCDS/bVVyxv6X4Cs0pAsASu1UXL+c9tXNSuFLRh8lNh4LkTTpVmzf4oE5rFoPaYJm8VXRbCqvgh37w5avjCx1hhbUdT8wAKEkPXpjNEsog0uyw8IomBRICnYvaSkcgx1EeCzW8kLW1xvzPsiYRGlJtaRxw0FiwIDAQABAoIBAQDDxkcpGeeeqYqon10Pz8bPa/r0SpiBl+uRmLtEI1NZSOQORHF7fA4ZjmVv9WcDsRXprWMMaaYsSi3u3zhkwOp4BiaaRG9IYomTSwLajZ2FxT2Tlh1nojE3lV+ZY2xPK6PqEMPK20Fbh1lDl+r4a80pyLhJsCbmMkUw0MiQf0ZejhxwcKEzw4PIJuUTgCpF8f03lh/MJWdluyYAOcUct00if1ktkOvQjxzyEXzZeUnIxHECvbX0xX6OhObGVE5spkAD9UOdUC3BpIEb1z4JjdDf8zhvaDlsWV5zpvdeKeQPRDFTB2vd0Zohh4hQ6TdQRw8vaZPbL8qea+0ROEEke4YZAoGBAPpEUqDuRWdmab/CSddID6Kc8qwQMZHvpRASwIkdZu+k+TImVySIBJ8fc9rqZbIOhrVhS2d8zaBubQEW+It4qccpefjkAbmFHW08oBHS+ab7nksahJlNJBz99GrpzAAPvTAR33+5tAXEN63oXtJvcX9/lrUDueGD4frDhHAQIbenAoGBAPDoTNhOyb1Irt5CfJapFeAFTl7JwsURHfHdFIej1ygTb4gTruoyt4pROOsMf0wiWPpadHZ7/3E75BxKktWZP+BEOF+51iOgmouuNu2vsKkuZakaygJNgZ6GcZdjfYa8sU7gE41v3GoEHLY+Uli5L6/N1z3kF8aUVFWxA3e/Af99AoGBAOQUhjVyUUA13qRLXd5cJxus66CSNYrpm0X1wRB1Ak3ezNi+hmadq5CVKpHVUw8eG/iLjhvnasMOQDthAuyg8CG5FBcXPNclkLbwLHVyD+H1qMKLjVLlMcdWTn1tS2S281UuxMBzrrQeqhvNDTW9KPPohKG9npb/CWDu9PDoUsI7AoGBANy/sLLBN4E4GezWNb4EgGP/2Llo3g2gSrU3JTnJez1g2eFyT+SQxrh7BtHzaK5GBwyZWIC9zOtguvzlpLkPrYV+Xb3x1vRclWELKZARXqsYNdWIE7WaefzeKzZS11Jgk4S4NZJz/yAyVnD0mJZuUvEgiGxRFyxC/ShshMX0hAstAoGBALs1m3OGpnf0b/z3Bt3S9X/7aszZA9hhaFFm24e1nqEDS92A8FVMhCM9V6p9eg0Cx83L4I2A0x5B/qYuDtpYpk1gtFTGZfpxMeqvaV1JVf72k4TWT9ixQ/123S8BXSHue7L4SFJEI6X9SAHR1o1m595w53gCIT96VMUl1oFLhYwU
    -----END RSA PRIVATE KEY-----"""


import djcelery  # 导入djcelery包
djcelery.setup_loader()  # 进行模块载入
BROKER_URL = 'redis://127.0.0.1:6379/1'  # 中间件  中间人 指定redis
BACKEND_URL='redis://127.0.0.1:6379/2'
CELERY_IMPORTS = ('CeleryTask.tasks')  # 具体的任务文件
CELERY_TIMEZONE = 'Asia/Shanghai'  # celery时区   跟django保持一致
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler' # django-celery的处理器，是固定的


from celery.schedules import timedelta,crontab

CELERYBEAT_SCHEDULE = {
    u'测试任务': {
        'task':'CeleryTask.tasks.test',  # 任务值函数
        'schedule':timedelta(seconds=1),  # 执行时间
    }
}





