# Generated by Django 2.2.1 on 2019-09-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='username',
            field=models.CharField(blank=True, default=1, max_length=32),
            preserve_default=False,
        ),
    ]
