# Generated by Django 2.2.1 on 2019-09-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_auto_20190924_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
