# Generated by Django 2.2.1 on 2019-09-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_orderinfo_payorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saller.LoginUser', verbose_name='店铺id'),
        ),
    ]
