# Generated by Django 2.2.1 on 2019-09-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_auto_20190925_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='goods_price',
            field=models.FloatField(default=10, verbose_name='商品单价'),
            preserve_default=False,
        ),
    ]
