# Generated by Django 2.2.1 on 2019-09-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0015_auto_20190928_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(2, '待发货'), (1, '已支付'), (3, '待收货'), (4, '完成'), (5, '拒收'), (0, '未支付')], verbose_name='订单状态'),
        ),
    ]
