# Generated by Django 2.2.1 on 2019-10-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0016_auto_20190929_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(2, '待发货'), (1, '已支付'), (0, '未支付'), (5, '拒收'), (3, '待收货'), (4, '完成')], verbose_name='订单状态'),
        ),
    ]
