# Generated by Django 2.2.1 on 2019-10-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0017_auto_20191008_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(4, '完成'), (1, '已支付'), (2, '待发货'), (0, '未支付'), (3, '待收货'), (5, '拒收')], verbose_name='订单状态'),
        ),
    ]
