# Generated by Django 2.2.1 on 2019-10-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0018_auto_20191016_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(1, '已支付'), (5, '拒收'), (2, '待发货'), (0, '未支付'), (4, '完成'), (3, '待收货')], verbose_name='订单状态'),
        ),
    ]
