# Generated by Django 2.2.1 on 2019-10-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0020_auto_20191016_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(0, '未支付'), (3, '待收货'), (5, '拒收'), (2, '待发货'), (1, '已支付'), (4, '完成')], verbose_name='订单状态'),
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
