# Generated by Django 2.2.1 on 2019-10-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0014_delete_useraddress'),
        ('Buyer', '0021_auto_20191016_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(0, '未支付'), (3, '待收货'), (5, '拒收'), (1, '已支付'), (2, '待发货'), (4, '完成')], verbose_name='订单状态'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('user_address', models.TextField()),
                ('user_code', models.CharField(max_length=32)),
                ('user_phone', models.CharField(max_length=11)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saller.LoginUser')),
            ],
        ),
    ]
