# Generated by Django 2.2.1 on 2019-10-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0022_auto_20191016_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.IntegerField(choices=[(5, '拒收'), (4, '完成'), (1, '已支付'), (3, '待收货'), (0, '未支付'), (2, '待发货')], default=0),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(5, '拒收'), (4, '完成'), (1, '已支付'), (3, '待收货'), (0, '未支付'), (2, '待发货')], verbose_name='订单状态'),
        ),
    ]
