# Generated by Django 2.2.1 on 2019-09-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=11)),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_price', models.FloatField()),
                ('goods_count', models.IntegerField()),
                ('goods_location', models.CharField(max_length=254)),
                ('goods_safe_date', models.IntegerField()),
                ('goods_status', models.IntegerField()),
                ('goods_pro_time', models.DateField(auto_now=True, verbose_name='生产日期')),
            ],
        ),
    ]
