# Generated by Django 2.2.1 on 2019-10-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0009_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
